apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotaemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kotaemon
  template:
    metadata:
      labels:
        app: kotaemon
    spec:
      containers:
      - name: kotaemon
        image: 825062525148.dkr.ecr.us-west-2.amazonaws.com/kotaemon:ktem-lite-with-dep-amd64
        imagePullPolicy: IfNotPresent
        env:
        - name: GRADIO_SERVER_NAME
          value: "0.0.0.0"
        - name: GRADIO_SERVER_PORT
          value: "7860"
        ports:
        - containerPort: 7860
        readinessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 40
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: kotaemon
spec:
  type: LoadBalancer
  selector:
    app: kotaemon
  ports:
  - name: http
    port: 7860
    targetPort: 7860